### ISSUE TITLE
The license isn't liable

### ISSUE THREAD

**Issue by Aspie96** [Open-Weights/Definition#10]
(I am not a lawyer and this is not legal advice).

From the license section "No Liability":

> As far as the law allows, each element is provided as is, without any warranty or condition, and the license will not be liable to anyone for any damages related to any licensed element or this license, under any kind of legal claim.

Shouldn't it say "the licensor will not be liable"? The license is a document, it can't be held liable.

(I do agree that the license, as written, is a FLOSS license and that preserving software freedom should be prioritized over other unrelated topics).

**Comment by heathermeeker** [comment]
Thanks for pointing this out!

**Comment by heathermeeker** [comment]
I made the change.
